### ISSUE TITLE
Issue with postcss 8.40

### ISSUE THREAD

**Issue by onigoetz** [swissquote/crafty#1338]
```
[15:22:42] 'css__lint' errored after 1.82 s
[15:22:42] TypeError in plugin "gulp-postcss"
Message:
    opts.node.rangeBy is not a function
Details:
    fileName: /home/sgoetz/workspace/sq/squp-archetype-example/server-war/src/main/frontend/css/Fieldset.scss
    domainEmitter: [object Object]
    domainThrown: false

Stack:
TypeError: opts.node.rangeBy is not a function
    at new Warning (/home/sgoetz/workspace/sq/squp-archetype-example/server-war/src/main/frontend/node_modules/stylelint-no-unsupported-browser-features/node_modules/postcss/lib/warning.js:9:29)
    at Result.warn (/home/sgoetz/workspace/sq/squp-archetype-example/server-war/src/main/frontend/node_modules/stylelint-no-unsupported-browser-features/node_modules/postcss/lib/result.js:26:19)
```

Works with 

```
  "resolutions": {
    "css_loader/postcss": "8.3.10",
    "doiuse/postcss": "8.3.10",
    "stylelint-no-unsupported-browser-features/postcss": "8.3.10"
  }
```

Seems to be introduced by https://github.com/postcss/postcss/releases/tag/8.4.0

**Comment by onigoetz** [comment]
Fixed in https://github.com/swissquote/crafty/releases/tag/v1.18.0
